"""votes models fkeys linking

Revision ID: 475ddce8f4ec
Revises: 5b2a47abf445
Create Date: 2024-09-19 01:31:38.360205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '475ddce8f4ec'
down_revision: Union[str, None] = '5b2a47abf445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('dao_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'proposals', 'daos', ['dao_id'], ['uuid'])
    op.drop_column('proposals', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.drop_column('proposals', 'dao_id')
    # ### end Alembic commands ###