"""daos models

Revision ID: 5b2a47abf445
Revises: 
Create Date: 2024-09-18 16:32:22.821497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b2a47abf445'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dao_uuid', table_name='dao')
    op.drop_table('dao')
    op.add_column('daos', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('daos', sa.Column('about', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daos', 'about')
    op.drop_column('daos', 'name')
    op.create_table('dao',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('members', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('short_desc', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name='dao_pkey')
    )
    op.create_index('ix_dao_uuid', 'dao', ['uuid'], unique=True)
    # ### end Alembic commands ###