""".

Revision ID: 7a3ae83be8af
Revises: aeb463bf440a
Create Date: 2024-09-19 17:05:36.454039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a3ae83be8af'
down_revision: Union[str, None] = 'aeb463bf440a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daos', sa.Column('created_by_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'daos', 'users', ['created_by_id'], ['uuid'])
    op.drop_column('daos', 'members')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daos', sa.Column('members', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'daos', type_='foreignkey')
    op.drop_column('daos', 'created_by_id')
    # ### end Alembic commands ###