"""added total_votes field to proposals

Revision ID: a03ef59aa9a1
Revises: 475ddce8f4ec
Create Date: 2024-09-19 02:15:08.921731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a03ef59aa9a1'
down_revision: Union[str, None] = '475ddce8f4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('total_votes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'total_votes')
    # ### end Alembic commands ###