"""Add cascade delete to Dao's created_by_id foreign key

Revision ID: a469f6574234
Revises: 6791a1533e45
Create Date: 2024-09-20 02:27:13.271368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a469f6574234'
down_revision: Union[str, None] = '6791a1533e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('daos_created_by_id_fkey', 'daos', type_='foreignkey')
    op.create_foreign_key(None, 'daos', 'users', ['created_by_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daos', type_='foreignkey')
    op.create_foreign_key('daos_created_by_id_fkey', 'daos', 'users', ['created_by_id'], ['uuid'])
    # ### end Alembic commands ###