"""Users table and linking with daos

Revision ID: aeb463bf440a
Revises: 658bb0cd9a0d
Create Date: 2024-09-19 17:00:18.370899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aeb463bf440a'
down_revision: Union[str, None] = '658bb0cd9a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daos', sa.Column('member_count', sa.Integer(), nullable=False))
    op.add_column('daos', sa.Column('created_by_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'daos', 'users', ['created_by_id'], ['uuid'])
    op.drop_column('daos', 'members')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daos', sa.Column('members', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'daos', type_='foreignkey')
    op.drop_column('daos', 'created_by_id')
    op.drop_column('daos', 'member_count')
    # ### end Alembic commands ###