"""Add cascade delete to Vote's created_by_id foreign key

Revision ID: d56b703ccb7a
Revises: 16839768063d
Create Date: 2024-09-20 03:27:14.346292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd56b703ccb7a'
down_revision: Union[str, None] = '16839768063d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###